# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3xnCey45gvRXxIX5wQWEA-m814-hoxv
"""

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

# Load shapefile
gdf = gpd.read_file("/content/Colombo/COLOMBO.shp")
# Display available columns
print("Available columns:", gdf.columns)
print("Columns DSD :", gdf["DSD_N"].unique())

# Plot the shapefile
gdf.plot(edgecolor='black', figsize=(10, 10))
plt.title("Map View of Shapefile")
plt.axis('off')
plt.show()
print(gdf)

# Step 1: Create the data
data = {
    'Division': [
        'Colombo MC', 'Kaduwela', 'Dehiwala', 'Kotte', 'Moratuwa', 'Kolonnawa',
        'Padukka', 'Maharagama', 'Kesbawa', 'Ratmalana',
        'Thimbirigasyaya', 'Seethawaka', 'Homagama'
    ],

    'Registered': [
        394533, 204547, 138460, 77162, 122567, 43470, 21876, 144675,
        154494, 40678, 101687, 113257, 216054
    ],
    'Voted': [
        227233, 115255, 71998, 41237, 77077, 25855, 15056, 79479,
        88200, 23425, 59635, 70607, 121554
    ]
}

# Step 2: Create DataFrame and calculate Unvoted and Unvoted percentage
df = pd.DataFrame(data)
df['Unvoted'] = df['Registered'] - df['Voted']
df['Unvoted_%'] = (df['Unvoted'] / df['Registered']) * 100

# Step 3: Print the table
print(df[['Division', 'Registered', 'Voted', 'Unvoted', 'Unvoted_%']].to_string(index=False, formatters={
    'Unvoted_%': '{:.2f}%'.format,
    'Registered': '{:,}'.format,
    'Voted': '{:,}'.format,
    'Unvoted': '{:,}'.format
}))

# Step 2: Load your shapefile (Colombo district with GNDs)
gdf = gpd.read_file("/content/Colombo/COLOMBO.shp")

# Check unique values to find correct match
print(gdf['DSD_N'].unique())  # Use 'DSD_N' for Division names

# Step 3: Merge on DSD_N (Divisional Secretariat Division Name)

# Clean up Division names to match DSD_N
df['Division'] = df['Division'].replace({
    'Colombo MC': 'COLOMBO',
    'Dehiwala': 'DEHIWALA',
    'Kaduwela': 'KADUWELA',
    'Kesbawa': 'KESBEWA',
    'Thimbirigasyaya': 'THIMBIRIGASYAYA',
    'Maharagama': 'MAHARAGAMA',
    'Moratuwa': 'MORATUWA',
    'Seethawaka': 'SEETHAWAKA',
    'Padukka': 'PADUKKA',
    'Kotte': 'SRI JAYAWARDANAPURA KOTTE',
    'Homagama': 'HOMAGAMA',
    'Ratmalana': 'RATMALANA',
    'Kolonnawa': 'KOLONNAWA'
})

merged = gdf.merge(df, left_on='DSD_N', right_on='Division')
print(merged.shape)  # Should be > 0

# Set up plot
fig, ax = plt.subplots(1, 1, figsize=(14, 14)) # Figure එක සහ එකම Axes එකක් create කරලා තියෙනවා, plot size එක 14 inch by 14 inch.
fig.patch.set_facecolor('#2c2c2c') # Sets the background color of the whole figure and the plotting area to a dark gray (#2c2c2c).
ax.set_facecolor('#2c2c2c')

# Defines a list of 13 different colors in HEX format for the divisions.
division_colors = [
    '#e6194b', '#3cb44b', '#ffe119', '#0082c8', '#f58231',
    '#911eb4', '#46f0f0', '#f032e6', '#d2f53c', '#fabebe',
    '#008080', '#e6beff', '#aa6e28'
]

# Extracts the unique division names from the merged GeoDataFrame.
unique_divisions = merged['Division'].unique()
division_color_map = dict(zip(unique_divisions, division_colors)) # Division name එකකට එක HEX color එක match කරන්න dictionary එකක් සාදලා තියෙනවා.
merged['Color'] = merged['Division'].map(division_color_map) # merged dataset එකට Color කියන නව column එකක් add කරලා, ඒකට division color assign කරනවා.

# Plots the map with the assigned colors, border lines of 1.2 thickness, and gray edges.
merged.plot(color=merged['Color'], linewidth=1.2, ax=ax, edgecolor='#888888')

# Sets the title of the map, with a font size of 18 and light gray color.
plt.title("Electoral Divisions - Colombo District\nWith Unvoted Percentage",
          fontsize=18, color='#f0f0f0')
plt.axis('off') # Hides the axis (no x/y labels).

# Drop duplicates to label only once per Division
labeled = merged.drop_duplicates(subset='Division')

# Annotate each with Division + %Unvoted - For every division in my map, place one label
for idx, row in labeled.iterrows():
    centroid = row.geometry.centroid
    label_text = f"{row['Division']}\n{row['Unvoted_%']:.1f}%"

#This places the label in the middle of each division.
    ax.text(
        centroid.x, centroid.y, label_text,
        ha='center', va='center',
        fontsize=8,
        color='white',
        bbox=dict(
            facecolor='black',
            edgecolor='white',
            boxstyle='round,pad=0.3',
            linewidth=0.8
        )
    )

plt.show()

